config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get "users/show" => "users#show"
  root 'pages#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :collections
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :users, only:[:index, :new, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "items/:id" => "items#show"
  get "collections/:id" => "collections#show"
  get "pages/show/:article_id", to: "pages#show"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many   :items, dependent: :destroy 
  mount_uploader :image, ImageUploader
  # validates :name, presence: true, unless: :image?
  validate :image_present?
  validate :name_present?
  validate :explanation_present?
  validates :name, :explanation, :image, :user, presence: true

  # 名前、説明、画像選択がない場合エラーとする
  def image_present?
    if image.blank?
      errors.add(:error, "画像のアップロードを選択してください。")
    end
  end
  def name_present?
    if name.blank?
      errors.add(:error, "名前を入力してください。")
    end
  end
  def explanation_present?
    if explanation.blank?
      errors.add(:error, "説明を入力してください。")
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :transition_destination, only:[:new]

  def index
    @collections = Collection.includes(:user).order('created_at DESC')
    @collection = Collection.includes(:items).order('created_at DESC')
  end

  def new
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      redirect_to collections_path      
    else
      render :new
    end
  end

  def edit
    @collection = find_collction_by_id
  end

  def update
    @collection = find_collction_by_id
    @collection.update(collection_params)
    redirect_to collections_path
  end

  def show
    @item = Item.where(collection_id: params[:id])
    @collection = find_collction_by_id
    @collections = Collection.includes(:user).order('created_at DESC')
  end

  def destroy
    collection = find_collction_by_id
    if collection.present?
        items = Item.where(collection_id: collection.id)
        items.each do |item|
          item.destroy
        end
        collection.destroy
        redirect_to root_path, notice: "削除しました。"
    else
        redirect_to collections_path, notice: "削除できませんでした。"
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:name,:explanation,:user_id,:image)
  end

  def find_collction_by_id
    Collection.find(params[:id])
  end

  def transition_destination
    @collection = Collection.new
    unless user_signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div class= "content">
  <div class= "remove_box__posts">
    <% if user_signed_in? && current_user.id == collection.user_id %>
      <%= link_to '投稿削除', collection_path(collection.id), method: :delete %>
      <%= link_to '投稿編集', edit_collection_path(collection.id) %>
    <% end %>
  </div>
  <%= link_to collection_path(collection.id), method: :get do %>
    <p> <%= image_tag collection.image.url, class:"content__image" %></p>
    <div class= "content__name">
      <p><%= collection.name %> </p>
    </div>
  <% end %>
</div>

app/views/collections/_form.html.erb
<% if user_signed_in? %>
  <%= form_for @collection, html:{class: "collection__form"} do |f| %>
    <%= render 'layouts/error_messages', model: f.object %> 
      部屋の名前<%= f.text_field :name, class:"collection__form__name" %><br>
      部屋の説明<%= f.text_area :explanation, class:"collection__form__explanation",size: "19x2" %>
      <%= f.label :image, "画像選択", class: "collection__form__label" %>
        <%= f.file_field :image, class:"collection__form__label__file" ,style: "display:none;"%>
      <%= f.hidden_field :user_id, value: current_user.id%>
      <%= f.submit "送信", class: "collection__form__submit"  %>
  <% end %>
<% end %>

app/views/collections/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/collections/destroy.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">戻る</a>
  </div>
</div>

app/views/collections/edit.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<%= render partial: 'form'%>

app/views/collections/index.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<div class = "collections">
  <%= render @collections %>
</div>

app/views/collections/new.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<%= render partial: 'form'%>

app/views/collections/show.html.erb
<div class= "container">
  <div class= "logo_wrapper">
    <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
  </div>
  <div class= "details_wrapper">
    <div class= "details_items">
      <% @item.each do |item| %>
        <% if item.image.present?%>
          <div class="remove_box">
            <div class="remove_box__posts">
              <% if user_signed_in? && current_user.id == item.user_id %>
                <%= link_to '投稿削除', item_path(item.id), method: :delete %>
                <%= link_to '投稿編集', edit_item_path(item.id) %>
              <% end %>
            </div>
            <%= link_to item_path(item), method: :get do %>
              <p><%= image_tag item.image.url, class:"content__image" %></p>
              <div class= "content__name">
                <p><%= item.title %> </p>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div >
  </div>
</div>