config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get "users/show" => "users#show"
  root 'pages#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :collections
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :users, only:[:index, :new, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "items/:id" => "items#show"
  get "collections/:id" => "collections#show"
  get "pages/show/:article_id", to: "pages#show"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  :confirmable, :lockable, :timeoutable, :trackable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :collections,  dependent: :destroy
  has_many :items,  dependent: :destroy
  has_many :favorites,  dependent: :destroy
  has_many :favorite_items, through: :favorites, source: :item
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :comments,  dependent: :destroy

  # フォローをしているか確認
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  # フォローをする
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォローを外す
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "松山 弘平"
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :following, :followers]

  def index
    if params[:follower]
      @relationships = Relationship.where(following_id: params[:user_id])
    elsif params[:following]
      @relationships = Relationship.where(follower_id: params[:user_id])
    end
  end

  def show
    @collections = Collection.includes(:items).order('created_at DESC')
    @items = Item.order('created_at DESC')
    @favorite_items = @user.favorite_items
  end

  def following
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @users = @user.followers
    render 'show_follower'
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      redirect_to edit_user_path(current_user)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {}).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
  
    <% if current_user.following?(@user) %>
      <div id="follow_form_<%= @user.id %>">
        <%= render "unfollow" %>
      </div>
    <% else %>
      <div id="follow_form_<%= @user.id %>">
        <%= render "follow" %>
      </div>
    <% end %>
  
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>

<h3>プロフィール編集</h3>

<div class="edit_profile">
  <%= form_with model: @user do |form| %>
    <div class="edit_profile__name">
      <%= form.text_field :name %>
    </div>
    <div class="edit_profile__email">
      <%= form.text_field :email %>
    </div>
    <div class="edit_profile__password">
      <%= form.text_field :password, placeholder: "password" %>
    </div>
    <div><%= form.submit "保存" %></div>
  <% end %>
</div>

app/views/users/index.html.erb
<% if params[:follower] %>
  <div class= "logo_wrapper">
    <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
  </div>
    <div class= "follower_title">フォロワー 一覧</div>
    <% @relationships.each do |relationship| %>
        <% @user = User.find_by(id: relationship.follower_id) %>
        <div class="users_contents">
            <div class= "users_wrapper">
                <div class= "follower_name">
                    <a href="/users/<%= @user.id %>"><%= @user.name %></a>
                </div>
                <div class= "follower_form">
                    <%= render "users/follow_form" %>
                </div>
            </div>
        </div>
        <br>
    <% end %>
<% elsif params[:following] %>
  <div class= "logo_wrapper">
    <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
  </div>
    <div class= "following_title">フォロー 一覧</div>
    <% @relationships.each do |relationship| %>
        <% @user = User.find_by(id: relationship.following_id) %>
        <div class="users_contents">
            <div class= "users_wrapper">
                <div class= "following_name">
                  <a href="/users/<%= @user.id %>"><%= @user.name %></a>
                </div>
                <div class= "following_form">
                    <%= render "users/follow_form" %>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/users/show.html.erb
<div class= "container">
  <%= render partial: 'pages/header' %>
  <div class= "layout_wrapper">
    <div class= "left_layout">
        <section class= "base_container">
          <div class= "user">
            <i class="fas fa-user fa-3x"></i>
            <div class="text">
              <span>ユーザー</span>
              <% if user_signed_in? && current_user %>
                <p class="name"> 
                  <%= @user.name %>
                </p>
              <% end %>
            </div>
          </div>
        </section>
        <section class="follow_container">
          <p class="container_title">status</p>
          <ul>
            <li>
              <p class="title">following</p>
              <div class="description">
                <a href="/users?following=1&user_id=<%=@user.id%>"><span id="following"><%= @user.following.count %></span>人</a>
              </div>
            </li>
            <li>
              <p class="title">follower</p>
              <div class="description">
                <a href="/users?follower=1&user_id=<%=@user.id%>"><span id="follower"><%= @user.followers.count %></span>人</a>
              </div>
            </li>
          </ul>
        </section>
      <div class= "following_form">
        <%= render "follow_form" %>
      </div>
    </div>
    <div class= "center_content">
      <h2>お気に入り内容</h2>
        <% @favorite_items.each do |item| %>
          <hr>
          <p><%=link_to item.explanation, item_path(item.id) %></p>
        <% end %>
          <hr>
    </div>
  </div>
</div>