config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get "users/show" => "users#show"
  root 'pages#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :collections
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :users, only:[:index, :new, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "items/:id" => "items#show"
  get "collections/:id" => "collections#show"
  get "pages/show/:article_id", to: "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many   :items, dependent: :destroy 
  mount_uploader :image, ImageUploader
  # validates :name, presence: true, unless: :image?
  validate :image_present?
  validate :name_present?
  validate :explanation_present?
  validates :name, :explanation, :image, :user, presence: true

  # 名前、説明、画像選択がない場合エラーとする
  def image_present?
    if image.blank?
      errors.add(:error, "画像のアップロードを選択してください。")
    end
  end
  def name_present?
    if name.blank?
      errors.add(:error, "名前を入力してください。")
    end
  end
  def explanation_present?
    if explanation.blank?
      errors.add(:error, "説明を入力してください。")
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to  :collection
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  validate :image_or_video_present?
  validate :collection_present?
  has_many :item_tags, dependent: :destroy 
  has_many :tags , through: :item_tags
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, :explanation, :user, :collection, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 画像もしくは動画がない場合エラーとする
  def image_or_video_present?
    if image.blank? && video.blank?
      errors.add(:error, "画像もしくは動画のアップロードを選択してください。")
    end
  end

  # コレクションを選択していない場合エラーとする
  def collection_present?
    if collection_id.blank?
      errors.add(:error, "コレクションを選択してください。")
    end
  end
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord
  belongs_to :tag
  belongs_to :item
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"

    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :item_tags, dependent: :destroy
  has_many :items , through: :item_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  :confirmable, :lockable, :timeoutable, :trackable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :collections,  dependent: :destroy
  has_many :items,  dependent: :destroy
  has_many :favorites,  dependent: :destroy
  has_many :favorite_items, through: :favorites, source: :item
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :comments,  dependent: :destroy

  # フォローをしているか確認
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  # フォローをする
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォローを外す
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "松山 弘平"
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :transition_destination, only:[:new]
  before_action :Find_Id_InTheItem, only:[:edit,:update,:show]
  def index
    @items = Item.includes(:user).order('created_at DESC')
  end

  def new
    @tags = Tag.all
    @collection = Collection.new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      @tags = Tag.all
      render :new
    end
  end
  
  def edit
    @tags = Tag.all
  end

  def update
    @item.update(item_params)
    redirect_to items_path
  end

  def show
    @items = Item.where(id: params[:id])
    @item = Item.find(params[:id])
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def destroy
    item = find_item_by_id
    if item.present?
        item.destroy
        redirect_to root_path, notice: "削除しました。"
    else
        redirect_to items_path, notice: "削除できませんでした。"
    end
  end

  def search
    @search = Item.ransack(params[:q])
    @search_items = @search.result(distinct: true)
  end

  private

  def item_params
    params.require(:item).permit(:title,:explanation,:image,:video,:user_id,:collection_id, tag_ids: [])
  end

  def find_item_by_id
    Item.find(params[:id])
  end

  def transition_destination
    @item = Item.new
    unless user_signed_in?
      redirect_to root_path
    end
  end  

  def Find_Id_InTheItem
    @item = find_item_by_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :move_to_index, except: [:index, :show]  

  def index
    @collections = Collection.includes(:items).order('created_at DESC')
    @items = Item.order('created_at DESC')
    @search = Item.ransack(params[:q])
    @search_items = @search.result(distinct: true)
  end

  def show
    # @collection = Collection.find(params[:id])
    # @item = Item.find(params[:id])
  end
  
  private
  
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :following, :followers]

  def index
    if params[:follower]
      @relationships = Relationship.where(following_id: params[:user_id])
    elsif params[:following]
      @relationships = Relationship.where(follower_id: params[:user_id])
    end
  end

  def show
    @collections = Collection.includes(:items).order('created_at DESC')
    @items = Item.order('created_at DESC')
    @favorite_items = @user.favorite_items
  end

  def following
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @users = @user.followers
    render 'show_follower'
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      redirect_to edit_user_path(current_user)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {}).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"
def text_url_to_link text
  URI.extract(text, ['http','https']).uniq.each do |url|
    sub_text = ""
    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

    text.gsub!(url, sub_text)
  end

  return text
end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any?  %>
  <div class="alert">
    <ul>
      <% model.errors.full_messages.each do |message|  %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PositiveLearning" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>
  <body>
<%# 
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PositiveLearning</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%# <li><%= link_to "Link1", "/path1"  %>
            <%# <li><%= link_to "Link2", "/path2"  %>
            <%# <li><%= link_to "Link3", "/path3"  %>
          <%# </ul> %>
        <%# </div>
      </div> %>
    <%# </div> %> 

    <%# <div class="container"> %>
      <%# <div class="row"> %>
        <%# <div class="col-lg-9"> %>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <%# <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %>
              <%# <li><%= link_to "Link2", "/path2"  %>
              <%# <li><%= link_to "Link3", "/path3"  %>
            <%# </ul> %> 
          <%# </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row--> %>
<%# 
      <footer>
        <p>&copy; Company 2020</p>
      </footer> %>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/_header.html.erb
<% if current_user %>
  <div class="upper_block">
    <div class="flex_wrapper_left">
      <div class="menu_panel_button">
        <div class= "icon_menu">
          <%= link_to "/pages/show/#{current_user.id}" do %>
            <i class= "fas fa-bars fa-2x" ></i>
          <% end %>
        </div>
      </div>
      <div class="logo">
        <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
      </div>
    </div>
    <div class= "flex_wrapper_right">
      <div class= "links">
        <ul>
          <li>
            <%= link_to 'COLLECTION', collections_path, class: "links_collection" %> 
          </li>
          <li>
            <%= link_to 'ITEM', items_path, class: "links_item" %> 
          </li>
        </ul>
      </div>
      <div class= "search">
        <%= search_form_for @search, url: search_items_path do |f| %>
          <%= f.label :title_or_explanation_cont, "Keyword", class: "icon-search" %>
            <span class="icon-search_icon">
                <i class="fas fa-search"></i>
            </span>
          <%= f.search_field :title_or_explanation_cont, class: "form-control", placeholder: "投稿検索" %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="upper_block">
    <div class="flex_wrapper_left">
      <div class="logo">
        <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
      </div>
    </div>
    <div class= "flex_wrapper_right">
      <div class= "links_box">
        <%= link_to 'New Registration', new_user_registration_path, class: "links_registration" %> 
        <%= link_to 'Login', new_user_session_path, class: "links_login" %> 
      </div>
      <div class= "search">
        <%= search_form_for @search, url: search_items_path do |f| %>
          <%= f.label :title_or_explanation_cont, "Keyword", class: "icon-search" %>
            <span class="icon-search_icon">
                <i class="fas fa-search"></i>
            </span>
          <%= f.search_field :title_or_explanation_cont, class: "form-control", placeholder: "投稿検索" %>
        <% end %>
      </div>
    </div>
  </div>
 <% end %>

app/views/pages/index.html.erb
<div class= "container">
  <%= render partial: 'header' %>
  <div class= "layout_wrapper">
    <div class= "left_layout">
      <section class= "base_container">
        <div class= "user">
          <i class="fas fa-user fa-3x"></i>
          <div class="text">
            <span>ユーザー</span>
            <% if user_signed_in? && current_user %>
              <p class="name"> 
                <%= current_user.name %>
              </p>
            <% end %>
          </div>
        </div>
      </section>
      <section class="follow_container">
        <p class="container_title">status</p>
        <ul>
          <li>
            <p class="title">following</p>
            <div class="description">
              <a href="/users?following=1&user_id=<%=current_user.id%>"><span id="following"><%= current_user.following.count %></span>人</a>
            </div>
          </li>
          <li>
            <p class="title">follower</p>
            <div class="description">
              <a href="/users?follower=1&user_id=<%=current_user.id%>"><span id="follower"><%= current_user.followers.count %></span>人</a>
            </div>
          </li>
        </ul>
      </section>
    </div>
    <div class="center_layout">
      <div class="swiper_container">
        <div class="swiper_slide">
          <div class="timeline_container">
            <div class="timeline_head">新規投稿</div> 
              <div class="timeline_card">
                <% @collections.each do |collection| %>
                  <% if collection.image.present?%>
                    <%= link_to collection_path(collection), method: :get do %>
                      <p><%= image_tag collection.image.url, class:"content__image" %></p>
                      <div class= "content__explanation">
                        <p><%= collection.explanation %> </p>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <div class="timeline_card_video">
                <% @items.each do |item| %>
                  <%= link_to item_path(item), method: :get do %>
                    <% if item.image.present? %>
                        <p><%= image_tag item.image.url, class:"content__image" %></p>
                    <% end %>
                    <% if item.video.present? %>
                      <%= video_tag item.video.url, type: "video/mp4", autoplay: true, muted: true, controls: true, preload: true, class:"content__video", height: "50%", width: "50%" %>
                    <% end %>
                      <div class= "content__explanation">
                        <p><%= item.explanation %> </p>
                      </div>
                  <% end %>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="menu">
  <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
  <div class="login_container">
    <div class="create_panel">
      <ul>
        <li>
          <%= link_to 'Follow', "/users?following=1&user_id=#{current_user.id}" , class: "links_box" %> 
        </li>
        <li>
          <%= link_to 'Follower', "/users?follower=1&user_id=#{current_user.id}" , class: "links_box" %> 
        </li>
        <li>
          <%= link_to 'Create Collection', new_collection_path , class: "links_box" %> 
        </li>
        <li>
          <%= link_to 'Create Item', new_item_path , class: "links_box" %> 
        </li>
        <li>
          <%= link_to 'Profile Settings', edit_user_registration_path(current_user) , class: "links_box" %> 
        </li>
        <li>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "links_box" %> 
        </li>
        <li>
          <%= link_to 'My Page', user_path(current_user), class: "links_box" %> 
        </li>
      </ul>
    </div>
  </div>
</div>