config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get "users/show" => "users#show"
  root 'pages#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :collections
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :users, only:[:index, :new, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "items/:id" => "items#show"
  get "collections/:id" => "collections#show"
  get "pages/show/:article_id", to: "pages#show"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to  :collection
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  validate :image_or_video_present?
  validate :collection_present?
  has_many :item_tags, dependent: :destroy 
  has_many :tags , through: :item_tags
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, :explanation, :user, :collection, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 画像もしくは動画がない場合エラーとする
  def image_or_video_present?
    if image.blank? && video.blank?
      errors.add(:error, "画像もしくは動画のアップロードを選択してください。")
    end
  end

  # コレクションを選択していない場合エラーとする
  def collection_present?
    if collection_id.blank?
      errors.add(:error, "コレクションを選択してください。")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :transition_destination, only:[:new]
  before_action :Find_Id_InTheItem, only:[:edit,:update,:show]
  def index
    @items = Item.includes(:user).order('created_at DESC')
  end

  def new
    @tags = Tag.all
    @collection = Collection.new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      @tags = Tag.all
      render :new
    end
  end
  
  def edit
    @tags = Tag.all
  end

  def update
    @item.update(item_params)
    redirect_to items_path
  end

  def show
    @items = Item.where(id: params[:id])
    @item = Item.find(params[:id])
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def destroy
    item = find_item_by_id
    if item.present?
        item.destroy
        redirect_to root_path, notice: "削除しました。"
    else
        redirect_to items_path, notice: "削除できませんでした。"
    end
  end

  def search
    @search = Item.ransack(params[:q])
    @search_items = @search.result(distinct: true)
  end

  private

  def item_params
    params.require(:item).permit(:title,:explanation,:image,:video,:user_id,:collection_id, tag_ids: [])
  end

  def find_item_by_id
    Item.find(params[:id])
  end

  def transition_destination
    @item = Item.new
    unless user_signed_in?
      redirect_to root_path
    end
  end  

  def Find_Id_InTheItem
    @item = find_item_by_id
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, html:{class: "item__form"} do |f| %>
 <%= render 'layouts/error_messages', model: f.object %> 
  タイトル<%= f.text_field :title, class:"item__form__name" %><br>
  アイテムの説明<%= f.text_area :explanation, class:"item__form__explanation",size: "19x2" %>
  <%= f.label :image, "画像選択", class: "item__form__label" %>
    <%= f.file_field :image, class:"item__form__label__file", style: "display:none;" %>
  <%= f.label :video, "動画選択", class:"item__form__videoLabel" %>
    <%= f.file_field :video, accept:'video/*',class:"item__form__videoLabel__field",style: "display:none;" %>
  <%= f.hidden_field :user_id, value: current_user.id%>
    <%= f.collection_select(:collection_id, Collection.where(user_id: current_user.id), :id, :name, prompt:true, class: "item__form__select") %>
  <div class="tag_field">
    <% if @tags.present? %>
      <% @tags.each do |t| %>
        <%= f.label t.name, class:"label_check_box" %>
        <%= check_box_tag "item[tag_ids][]", t.id, @item.tags.include?(t),class:"check_box" %>
        <br/>
      <% end %>
    <% end %>
  </div>
  <%= f.submit "送信", class: "item__form__submit"  %>
<% end %>

app/views/items/_item.html.erb
<div class= "content">
  <div class= "remove_box__posts">
    <% if user_signed_in? && current_user.id == item.user_id %>
      <%= link_to '投稿削除', item_path(item.id), method: :delete %>
      <%= link_to '投稿編集', edit_item_path(item.id) %>
    <% end %>
  </div>
  <%= link_to item_path(item), method: :get do %>
    <% if item.image.present? %>
      <p> <%= image_tag item.image.url, class:"content__image" %> </p>
    <% end %>
    <% if item.video.present? %>
      <p> <%= video_tag item.video.url, type: "video/mp4", autoplay: true, muted: true, controls: true, preload: true, class:"content__video", height: "100%", width: "100%" %></p>
    <% end %>
    <div class= "content__name">
      <p><%= item.title %> </p>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<%= render partial: 'form'%>

app/views/items/index.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<div class = "items">
  <%= render @items %>
</div>

app/views/items/new.html.erb
<%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
<%= render partial: 'form'%>

app/views/items/search.html.erb
<h1>検索結果</h1>
<div class= "search_results">
  <div class= "content">
    <% if @search_items.present?%>
      <% @search_items.each do |search_item| %>
        <div class= "content_box">
          <%= link_to item_path(search_item.id), method: :get do %>
            <p> <%= image_tag search_item.image.url, class:"content__image", height: "100%", width: "80%" %> </p>
            <p> <%= video_tag search_item.video.url, type: "video/mp4", autoplay: true, muted: true, controls: true, preload: true, class:"content__video", height: "20%", width: "20%" unless search_item.video.blank? %></p>
            <div class= "content__explanation">
              <p><%= search_item.explanation %> </p>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <%= link_to "お探しの投稿はありませんでした。TOPページへ戻る", '/', class: "back" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class= "container">
  <div class= "logo_wrapper">
    <%= link_to image_tag('logo.png', alt:"positive-learning", class: "service_logo"), '/' %>
  </div>
  <div class= "outline_container">
    <div class= "details_items">
      <div class= "item_video_wrapper">
        <% @items.each do |item| %>
          <div class= "favorites_box">
            <% if user_signed_in? %>
              <%= link_to "投稿者プロフィール", "/users/#{@item.user_id}" %>
              <% if item.favorited_by?(current_user) %> 
                  <p><span>お気に入り解除: </span><%=link_to item.favorites.count, item_favorites_path(item.id), method: :delete %></p>
              <% else %>
                  <p><span>お気に入り登録: </span><%=link_to item.favorites.count, item_favorites_path(item.id), method: :post %></p>
              <% end %>
            <% else %>
              <p><span>お気に入り数: </span><%= item.favorites.count %></p>
            <% end %>
          </div>
          <% if item.image.present?%>
            <div class= "details_items__image">
              <%= image_tag ("#{item.image}") %>
            </div>
          <% end %>
          <% if item.video.present? %>
            <div class= "details_items__video">
            <p> <%= video_tag item.video.url, type: "video/mp4", autoplay: true, muted: true, controls: true, preload: true, class:"content__video", height: "100%", width: "100%" %></p>
            </div>
          <% end %>
      </div>
          <div class= "flex_wrapper">
            <div class= "remove_box__posts">
              <% if user_signed_in? && current_user.id == @item.user_id %>
                <%= link_to '投稿削除', item_path(@item.id), method: :delete %>
                <%= link_to '投稿編集', edit_item_path(@item.id) %>
              <% end %>
            </div>
            <div class= "details_items__title">
              <p><%= item.title %></p>
            </div>
            <div class= "details_items__explanation">
              <%= text_url_to_link(h(item.explanation)).html_safe %>
            </div>
          </div>
        <% end %>
    </div>
    <div class= "comment_block">
      <div class= "comment_section">
        <div class= "comment_title">
          <h4>コメント</h4>
        </div>
        <div class= "comment_text">
          <%= form_with model: [@item, @comment], method: :post, local:true do |f| %>
            <%= f.text_area :content, autofocus: true %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.submit 'コメントする', class: "comment_submit" %>
          <% end %>
        </div>
      </div>
      <div class= "comment_wrapper">
        <% @comments.each do |c| %>
          <div class= "comment_wrapper__box">
            <div class= "comment_wrapper__NameBox">
              <div class= "comment_wrapper__NameBox__name">
                <a href="/users/<%= c.user.id %>"><%= c.user.name %></a>
              </div>
              <% if user_signed_in? && current_user.id == c.user_id %>
                <div class= "comment_wrapper__NameBox__delete">
                  <p><%= link_to "コメント削除", item_comment_path(c.item.id, c.id), method: :delete %></p>
                </div>
              <% end %>
            </div>
              <p><span>コメント内容: </span><%= c.content %></p>
          </div>
        <% end %>
      </div>
    </div>
    <hr>
  </div>
</div>